"""Frozen bench-pack gate — the charter's external-fitness acceptance layer.

Charter (演进方案.md §5.2, 配对会话): one ``evolver.bench`` task pack becomes
an additional solidify acceptance condition, and **only a strict improvement
publishes**. A drop, a flat score, an unmeasured replicate, a missing pack,
and a damaged gate ALL reject — and a reject never moves the baseline. The
earlier rule ("flat passes, only a drop rejects") is exactly what let a
mutation that merely retuned the measuring instrument ship. The scoring
rules live OUT-OF-REPO on the anchor side (``$EVOLVER_HOME/anchor/bench/``),
read-only in-cycle: an in-cycle mutation cannot weaken its own gate.

Freeze is a deterministic setup action (``evolver bench freeze``): it writes
the built-in pack to the canonical path and is idempotent without
``--force`` (re-freezing is a human decision — the instrument forbids it).
The gate grades the pack's ``val`` split sandboxes as they stand. WHO solves
val is a separate-context question: the candidate-writing host must not be
the one answering the sealed questions, so until that context exists the
honest verdict for an unsolved split is *unmeasured → reject*.

Baseline semantics: the persisted score of the last ACCEPTED state. Nothing
has been accepted yet → there is no bar, and a measurement must never write
its own result into it (a strong first candidate would raise the bar to
itself and become unrepeatable; a weak one would sink it below Parent and
let regressions read as improvements). The Parent bar is set once by a
separate, mutation-free measurement — :func:`establish_parent_baseline` /
``evolver bench baseline`` — the only first-baseline writer, unreachable
from solidify. A re-frozen pack voids the bar (``rekeyed_void``) and does
NOT silently rebuild it.

No new ``EVOLVER_*`` knobs — the gate is armed by the frozen pack's
existence, nothing else.

No Node.js equivalent; evolver.py self-research addition (charter 2026-09-24).
"""

from __future__ import annotations

import hashlib
import json
import math
import time
from pathlib import Path
from typing import Any, Final

from evolver.bench.builtin_pack import write_pack
from evolver.bench.compare import compare_runs
from evolver.bench.regression_guard import (
    REASON_NO_FLOOR_SOURCE,
    REASON_REGRESSION,
    assert_no_regression,
    floors_from_declaration,
    violators,
)
from evolver.bench.scoring import grade
from evolver.bench.tasks import validate_tasks
from evolver.gep.anchor import anchor_dir
from evolver.gep.paths import get_gep_assets_dir

#: Anchor-side gate directory (outside every workspace — 环内只读).
CHARTER_PACK_SUBDIR: Final = "bench"
CHARTER_PACK_FILENAME: Final = "charter-pack.tasks.json"
#: Baseline record format marker. v1 adds ``per_task`` — the Parent's own
#: score on every val task, which is what the no-regression floors are built
#: from. A v0 record carries no floors, so it cannot assert anything, and an
#: unassertable floor rejects (演进方案.md §5.2).
BASELINE_FORMAT: Final = "evolver.bench_pack_baseline.v1"
#: The gate only gates on the val split (S26.4: gate ONLY on val).
GATE_SPLIT: Final = "val"


def frozen_pack_path() -> Path:
    """Canonical anchor-side frozen pack path."""
    return anchor_dir() / CHARTER_PACK_SUBDIR / CHARTER_PACK_FILENAME


#: Independent val solve rounds required for a small validation split
#: (演进方案.md §5.2: a small val split needs a second same-direction score).
#: The built-in pack is 12 tasks = train 7 / val 5 - note ``spec-pipe-2`` is
#: generated by a comprehension and carries no ``-val`` suffix, so grepping
#: for the literal split only counts 4 of the 5.
#: Two independent host solves must BOTH beat the Parent.
REPLICATES: Final = 2
#: A val split this size or smaller cannot carry a decision on one solve.
REPLICATE_VAL_MAX: Final = 6
#: Big-pack publish rule: once the human-installed pack holds MORE val tasks
#: than :data:`REPLICATE_VAL_MAX`, publication is decided by the paired
#: per-task comparison (:mod:`evolver.bench.compare`) at this alpha instead
#: of the two-replicates-strictly-above rule.
COMPARE_ALPHA: Final = 0.05
#: Minimum discordant pairs a big-pack publish must show. Below this the
#: split — however large — has not produced enough disagreement to carry a
#: decision, and "no significant difference" is the honest verdict.
COMPARE_MIN_DISCORDANT: Final = 8


def sandbox_root(pack_path: Path, *, replicate: int | None = None) -> Path:
    """Sandboxes live next to the pack (same layout as ``bench run``).

    ``replicate`` selects an independent solve slot: the small-pack rule asks
    the host to solve val twice, and the two runs must not overwrite each
    other. ``replicate=None`` keeps the historical flat layout.
    """
    base = pack_path.resolve().parent / "sandboxes"
    return base / f"r{replicate}" if replicate is not None else base


def _round_root(pack_path: Path, replicate: int | None) -> Path:
    return sandbox_root(pack_path, replicate=replicate)


def pack_digest(path: Path) -> str:
    """Short SHA-256 of the frozen pack bytes — binds the baseline to the
    exact scoring rules it was established under."""
    return hashlib.sha256(path.read_bytes()).hexdigest()[:16]


def freeze_charter_pack(*, force: bool = False) -> dict[str, Any]:
    """Write the built-in pack to the frozen gate path. Idempotent without
    *force*: an existing frozen pack is never silently replaced (a weaker
    pack must not be freezable from inside a cycle)."""
    path = frozen_pack_path()
    if path.exists() and not force:
        return {
            "path": str(path),
            "frozen": False,
            "digest": pack_digest(path),
            "tasks": len(json.loads(path.read_text(encoding="utf-8")).get("tasks") or []),
        }
    written = write_pack(path)
    tasks = json.loads(written.read_text(encoding="utf-8")).get("tasks") or []
    return {
        "path": str(written),
        "frozen": True,
        "digest": pack_digest(written),
        "tasks": len(tasks),
    }


def load_frozen_pack() -> tuple[list[dict[str, Any]], str] | None:
    """(tasks, digest) of the frozen pack, or ``None`` when absent/invalid —
    an unusable pack degrades the gate to inactive, never crashes solidify."""
    path = frozen_pack_path()
    if not path.exists():
        return None
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
        tasks = raw.get("tasks") if isinstance(raw, dict) else raw
        if not isinstance(tasks, list) or validate_tasks(tasks):
            return None
        return tasks, pack_digest(path)
    except (OSError, json.JSONDecodeError, ValueError):
        return None


# ---------------------------------------------------------------------------
# Baseline: the last-accepted pack score (drop detector, not r_best)
# ---------------------------------------------------------------------------


def baseline_path() -> Path:
    return get_gep_assets_dir() / "acceptance" / "bench_pack_baseline.json"


def load_baseline() -> dict[str, Any] | None:
    """Persisted last-accepted record, or ``None`` when absent/corrupt."""
    path = baseline_path()
    if not path.exists():
        return None
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    if not isinstance(payload, dict):
        return None
    score = payload.get("score")
    # A NaN bar is worse than no bar: every comparison against it is False,
    # which silently turns "must beat the Parent" into "may do anything".
    if not isinstance(score, (int, float)) or isinstance(score, bool) or not math.isfinite(score):
        return None
    return payload


def save_baseline(score: float, digest: str, per_task: dict[str, float] | None = None) -> None:
    path = baseline_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "format": BASELINE_FORMAT,
        "score": score,
        "pack_digest": digest,
        "split": GATE_SPLIT,
        # The Parent's own per-task scores — the floors the no-regression
        # assertion is built from. Absent means "cannot assert", not "waived".
        "per_task": per_task or {},
        # The acceptance protocol this bar was measured under. Comparing
        # against it after the suite is re-seeded would be measuring with a
        # ruler that changed mid-comparison.
        "anchor_epoch": _current_anchor_epoch(),
        "updated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    }
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def per_task_floors(rounds: list[dict[str, Any]]) -> dict[str, float]:
    """Per-task floors from measured rounds: each task's LOWEST replicate.

    Lowest, not average: the floor is the water level the Parent actually
    held in every solve, so a candidate is only refused when it falls under
    the Parent's worst confirmed showing — never for failing to repeat the
    Parent's luckiest one.
    """
    floors: dict[str, float] = {}
    for round_data in rounds or []:
        for entry in round_data.get("per_task") or []:
            if not isinstance(entry, dict) or entry.get("status") != "graded":
                continue
            tid = str(entry.get("id") or "")
            score = entry.get("score")
            if not tid or not isinstance(score, (int, float)) or isinstance(score, bool):
                continue
            if not math.isfinite(score):
                continue
            value = float(score)
            floors[tid] = value if tid not in floors else min(floors[tid], value)
    return floors


def _gate_task_ids() -> dict[str, list[str]] | None:
    """Train/val ids to check a candidate's declaration against, or ``None``
    when the pack is unarmed. An unarmed pack has no train list, and an empty
    one would reject every declaration for the wrong reason."""
    try:
        from evolver.gep.val_seal import task_ids

        ids = task_ids()
    except Exception:
        return None
    return ids if ids.get("train") else None


def _current_anchor_epoch() -> int | None:
    """The installed anchor suite's epoch — one half of the acceptance
    protocol a baseline was established under (the other half is the pack
    digest). ``None`` when no suite is installed."""
    try:
        from evolver.gep.anchor import load_epoch

        epoch = load_epoch()
    except Exception:
        return None
    if not isinstance(epoch, dict):
        return None
    value = epoch.get("epoch")
    return int(value) if isinstance(value, int) and not isinstance(value, bool) else None


def _protocol_matches(baseline: dict[str, Any]) -> bool:
    """Whether the protocol that produced the bar is still the one running.

    A re-frozen pack already voids the bar via the digest. Anchoring the
    epoch closes the other half: the frozen contracts can be re-seeded
    (``anchor init --epoch N``) without the pack bytes changing, and a bar
    measured under the old suite must not judge a candidate under the new.
    """
    return baseline.get("anchor_epoch") == _current_anchor_epoch()


# ---------------------------------------------------------------------------
# Grading + verdict
# ---------------------------------------------------------------------------


def grade_split(
    tasks: list[dict[str, Any]],
    root: Path,
    *,
    split: str = GATE_SPLIT,
) -> tuple[list[dict[str, Any]], float | None, list[str]]:
    """Grade one split's sandboxes as they stand. Quiet core of
    ``gate_verdict`` — no prints, no ledger write (the gate is a decision,
    not a measurement claim).

    **All-or-nothing**: if ANY task of the split is still pending (its
    sandbox absent), the whole replicate is unmeasured and scores ``None``.
    A partial solve must not be averaged into a verdict — one lucky task
    above the bar is not a measurement of the candidate.

    Returns ``(per_task, score_or_None, pending_ids)``.
    """
    per_task: list[dict[str, Any]] = []
    pending: list[str] = []
    earned = 0.0
    counted = 0
    for task in tasks:
        if task.get("split") != split:
            continue
        tid = str(task["id"])
        sb = root / tid
        if not sb.exists():
            per_task.append({"id": tid, "status": "pending"})
            pending.append(tid)
            continue
        task_score = grade(task, sb)
        earned += task_score
        counted += 1
        per_task.append({"id": tid, "status": "graded", "score": task_score})
    if pending:
        return per_task, None, pending
    return per_task, (round(earned / counted, 4) if counted else None), []


def _parent_run(baseline: dict[str, Any]) -> dict[str, Any] | None:
    """The Parent's per-task record reshaped as a run for the paired test.

    ``None`` when the baseline carries no usable ``per_task`` dict — without
    the Parent's own per-task scores there is nothing to pair against, and
    an unpairable bar rejects (same refusal family as the floor assertion).
    """
    raw = baseline.get("per_task")
    if not isinstance(raw, dict) or not raw:
        return None
    rows: list[dict[str, Any]] = []
    for tid, value in raw.items():
        if not isinstance(value, (int, float)) or isinstance(value, bool):
            return None
        if not math.isfinite(float(value)):
            return None
        rows.append({"id": str(tid), "score": float(value)})
    return {"per_task": rows}


def _paired_verdict(
    payload: dict[str, Any],
    baseline: dict[str, Any],
    digest: str,
    declaration: dict[str, Any] | None,
    rounds: list[dict[str, Any]],
) -> dict[str, Any]:
    """Big-pack decision: the paired test replaces the mean-vs-bar rule.

    A split too large for a one-solve decision (val > ``REPLICATE_VAL_MAX``)
    publishes on statistical evidence: the candidate's graded per-task
    results are paired against the Parent's own per-task record and judged
    by an exact two-sided binomial test on the discordant pairs
    (:mod:`evolver.bench.compare`). Publish requires EVERY graded round to
    show the candidate winning the direction (p <= alpha) with at least
    ``COMPARE_MIN_DISCORDANT`` discordant pairs.

    The raw-score floors do not run here: with the Parent's exact scores as
    per-task floors a paired candidate could never lose a single task, and
    the test would be unreachable. On a big pack the no-regression
    protection IS the paired test — a collapsed task is a lost pair, counted
    against significance. The candidate's own declaration still binds.
    """
    parent = _parent_run(baseline)
    if parent is None:
        payload["reason"] = REASON_NO_FLOOR_SOURCE
        return payload

    # The candidate's own declaration binds on every pack size — a promise
    # the candidate made is asserted, not waived because the pack is big.
    declared, decl_reason = floors_from_declaration(declaration, task_ids=_gate_task_ids())
    if decl_reason:
        payload["reason"] = decl_reason
        return payload
    if declared:
        found, _unmeasured = violators([r["per_task"] for r in rounds], declared)
        if found:
            payload["reason"] = REASON_REGRESSION
            payload["regression"] = {
                "ok": False,
                "reason": REASON_REGRESSION,
                "violations": found,
            }
            return payload

    comparisons: list[dict[str, Any]] = []
    for round_data in rounds:
        try:
            result = compare_runs({"per_task": round_data["per_task"]}, parent, alpha=COMPARE_ALPHA)
        except ValueError as exc:
            # Task sets differ — the baseline was measured on another split.
            # A comparison would be meaningless, so refuse instead of crash.
            payload["reason"] = "task_set_mismatch"
            payload["detail"] = str(exc)
            return payload
        comparisons.append({"replicate": round_data.get("replicate"), **result})

    payload["verdict_mode"] = "paired_compare"
    payload["compare"] = comparisons

    if all(
        c["verdict"] == "a_better" and c["discordant"] >= COMPARE_MIN_DISCORDANT
        for c in comparisons
    ):
        aggregate = float(payload["score"])
        save_baseline(aggregate, digest, per_task=per_task_floors(rounds))
        payload["accept"] = True
        payload["verdict"] = "accept"
        payload["reason"] = "paired_improvement"
        payload["baseline"] = aggregate
        payload["delta"] = round(aggregate - float(baseline["score"]), 4)
        return payload

    if any(c["verdict"] == "b_better" for c in comparisons):
        payload["reason"] = "parent_better"
    elif any(c["discordant"] < COMPARE_MIN_DISCORDANT for c in comparisons):
        payload["reason"] = "not_enough_discordant"
        payload["discordant"] = min(c["discordant"] for c in comparisons)
    else:
        payload["reason"] = "no_significant_difference"
    payload["delta"] = round(float(payload["score"]) - float(baseline["score"]), 4)
    return payload


def gate_verdict(
    *,
    require_replicate: bool | None = None,
    declaration: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Grade the frozen pack's val split and decide against the baseline.

    Charter flip (演进方案.md §5.2): **only a strict improvement publishes.**
    A drop, a flat score, an unmeasured split, a damaged gate, a missing pack,
    or a voided baseline all reject - and a reject never moves the baseline.
    The previous rule ("flat is a pass, only a drop rejects") is exactly what
    let a mutation that merely retuned the measuring instrument ship.

    Small packs must also survive two *independent* host solves, both beating
    the Parent - one lucky run does not count as reproducible. A big pack
    (val > ``REPLICATE_VAL_MAX``) publishes through the paired per-task
    comparison instead (:func:`_paired_verdict`).

    Beating the mean is not enough on its own: a candidate can raise the mean
    while collapsing one task, so the per-task floors are asserted too
    (:mod:`evolver.bench.regression_guard`). *declaration* carries the
    candidate's own additions and may only tighten, never loosen.

    Always returns a dict. There is no longer a ``None`` "gate inactive"
    state: an unusable gate is a reject, never a pass.
    """
    pack_path = frozen_pack_path()
    base: dict[str, Any] = {
        "armed": False,
        "accept": False,
        "verdict": "reject",
        "pack": str(pack_path),
        "split": GATE_SPLIT,
        "replicates": 1,
        "scores": [],
        "baseline": None,
    }

    try:
        loaded = load_frozen_pack()
    except Exception as exc:
        return {**base, "reason": "gate_error", "detail": f"pack read failed: {exc}"}

    if loaded is None:
        return {**base, "reason": "pack_absent"}

    tasks, digest = loaded
    val_count = sum(1 for t in tasks if t.get("split") == GATE_SPLIT)
    need = (
        (val_count <= REPLICATE_VAL_MAX) if require_replicate is None else bool(require_replicate)
    )
    replicates = REPLICATES if need else 1

    rounds: list[dict[str, Any]] = []
    pending_ids: list[str] = []
    try:
        for index in range(1, replicates + 1):
            per_task, score, pending = grade_split(
                tasks, _round_root(pack_path, index if need else None)
            )
            rounds.append({"replicate": index, "score": score, "per_task": per_task})
            pending_ids.extend(pending)
    except Exception as exc:
        return {**base, "digest": digest, "reason": "gate_error", "detail": str(exc)}

    scores = [round_data["score"] for round_data in rounds]
    baseline = load_baseline()
    rekeyed = baseline is not None and baseline.get("pack_digest") != digest
    if rekeyed:
        baseline = None  # the rules changed; the old bar is void

    payload = {
        **base,
        "armed": True,
        "digest": digest,
        "val_tasks": val_count,
        "replicates": replicates,
        "scores": scores,
        "rounds": rounds,
        "baseline": float(baseline["score"]) if baseline is not None else None,
    }

    if baseline is not None and not _protocol_matches(baseline):
        # The suite was re-seeded under our feet. The bar is not void by
        # choice — it is simply no longer the same measurement, and no
        # verdict may be drawn from it until a human re-measures the Parent.
        payload["reason"] = "protocol_drift"
        payload["anchor_epoch"] = _current_anchor_epoch()
        payload["baseline_epoch"] = baseline.get("anchor_epoch")
        return payload

    if any(score is None for score in scores):
        # One unsolved task in any replicate is enough: a partial solve is not
        # a measurement of the candidate, and the baseline stays where it is.
        payload["reason"] = "unmeasured"
        payload["score"] = None
        payload["pending_tasks"] = sorted(set(pending_ids))
        return payload

    if any(not math.isfinite(float(score)) for score in scores if score is not None):
        # A NaN mean is not a measurement: it compares False against every bar
        # and would otherwise fall through to the "flat" branch, reading as a
        # near miss instead of the refusal it is.
        payload["reason"] = "non_finite_score"
        payload["score"] = None
        return payload

    aggregate = round(sum(scores) / len(scores), 4)
    payload["score"] = aggregate

    if baseline is None:
        # No bar exists yet — and this measurement must NOT write one from its
        # own result. Charter: the baseline is the last ACCEPTED score; before
        # any Accept there is no bar. Letting the first candidate set it has
        # two death traps: a strong candidate raises the bar to itself and the
        # same improvement can never be accepted again; a weak one sinks the
        # bar below Parent so later regressions read as "strictly better".
        # The Parent bar comes from a separate, mutation-free measurement
        # (establish_parent_baseline / `evolver bench baseline`).
        payload["reason"] = "rekeyed_void" if rekeyed else "no_baseline"
        return payload

    if val_count > REPLICATE_VAL_MAX:
        # Big pack: the human installed more val tasks than a one-solve
        # decision can carry, so publication moves to the paired comparison
        # (bench/compare.py, alpha = 0.05). The small pack below keeps the
        # two-replicates-strictly-above rule.
        return _paired_verdict(payload, baseline, digest, declaration, rounds)

    bar = float(baseline["score"])
    worst = min(scores)
    if worst > bar:
        # Beating the mean is necessary, not sufficient: assert the per-task
        # floors before publishing. A regression here is still a reject, and
        # it never moves the baseline either.
        floors = assert_no_regression(
            [round_data["per_task"] for round_data in rounds],
            baseline=baseline,
            declaration=declaration,
            task_ids=_gate_task_ids(),
        )
        payload["regression"] = {
            "ok": floors["ok"],
            "reason": floors["reason"],
            "violations": floors["violations"],
        }
        if not floors["ok"]:
            payload["reason"] = str(floors["reason"])
            return payload
        save_baseline(aggregate, digest, per_task=per_task_floors(rounds))
        payload["accept"] = True
        payload["verdict"] = "accept"
        payload["reason"] = "strict_improvement"
        payload["baseline"] = aggregate
        payload["delta"] = round(aggregate - bar, 4)
        return payload

    payload["reason"] = "flat" if worst == bar else "drop"
    payload["delta"] = round(aggregate - bar, 4)
    payload["worst_replicate"] = worst
    return payload


def establish_parent_baseline() -> dict[str, Any]:
    """Measure the CURRENT val sandboxes as the Parent bar — mutation-free.

    This is the ONLY writer of a first baseline, and it is deliberately
    unreachable from solidify: a candidate must never measure itself into the
    bar it will be judged against. Run it once per pack (``evolver bench
    baseline``) after the Parent's val sandboxes are in place.

    Requires every val task graded in every replicate slot — a partial Parent
    measurement is no measurement, and an unsolved Parent is not a bar.
    """
    pack_path = frozen_pack_path()
    loaded = load_frozen_pack()
    if loaded is None:
        return {
            "ok": False,
            "reason": "pack_absent",
            "pack": str(pack_path),
            "baseline": None,
        }
    tasks, digest = loaded
    val_count = sum(1 for t in tasks if t.get("split") == GATE_SPLIT)
    if val_count == 0:
        return {"ok": False, "reason": "no_val_tasks", "pack": str(pack_path)}

    need = val_count <= REPLICATE_VAL_MAX
    replicates = REPLICATES if need else 1
    scores: list[float] = []
    rounds: list[dict[str, Any]] = []
    pending: list[str] = []
    for index in range(1, replicates + 1):
        per_task, score, pending_ids = grade_split(
            tasks, _round_root(pack_path, index if need else None)
        )
        rounds.append({"replicate": index, "score": score, "per_task": per_task})
        pending.extend(pending_ids)
        if score is None:
            return {
                "ok": False,
                "reason": "unmeasured",
                "pack": str(pack_path),
                "digest": digest,
                "val_tasks": val_count,
                "replicates": replicates,
                "rounds": rounds,
                "pending_tasks": sorted(set(pending)),
                "baseline": None,
            }
        scores.append(score)

    aggregate = round(sum(scores) / len(scores), 4)
    existing = load_baseline()
    # The Parent's per-task scores are the floors every later candidate must
    # hold — without them the no-regression assertion has nothing to assert.
    save_baseline(aggregate, digest, per_task=per_task_floors(rounds))
    return {
        "ok": True,
        "reason": "parent_baseline_written",
        "pack": str(pack_path),
        "digest": digest,
        "val_tasks": val_count,
        "replicates": replicates,
        "score": aggregate,
        "rounds": rounds,
        "previous_baseline": (float(existing["score"]) if existing is not None else None),
        "baseline": aggregate,
    }


def gate_snapshot() -> dict[str, Any]:
    """Cheap state for ``swarm_status`` / the instrument — no grading."""
    loaded = load_frozen_pack()
    if loaded is None:
        return {"armed": False, "pack": str(frozen_pack_path())}
    tasks, digest = loaded
    val_tasks = sum(1 for t in tasks if t.get("split") == GATE_SPLIT)
    baseline = load_baseline()
    return {
        "armed": True,
        "pack": str(frozen_pack_path()),
        "digest": digest,
        "val_tasks": val_tasks,
        "baseline": (float(baseline["score"]) if baseline is not None else None),
        "baseline_digest": (str(baseline.get("pack_digest")) if baseline else None),
    }


__all__ = [
    "BASELINE_FORMAT",
    "CHARTER_PACK_FILENAME",
    "CHARTER_PACK_SUBDIR",
    "COMPARE_ALPHA",
    "COMPARE_MIN_DISCORDANT",
    "GATE_SPLIT",
    "baseline_path",
    "establish_parent_baseline",
    "freeze_charter_pack",
    "frozen_pack_path",
    "gate_snapshot",
    "gate_verdict",
    "grade_split",
    "load_baseline",
    "load_frozen_pack",
    "pack_digest",
    "sandbox_root",
    "save_baseline",
]
