"""Soak environment — keep evolution runtime off the product git tree.

演进方案.md §10: gated_runs 4→20 must use an ``EVOLUTION_DIR`` outside the
repo so daemon/swarm writes do not dirty ``master``. This module creates that
layout under ``$EVOLVER_HOME/evolver.py-soak/`` and reports whether the
current process is still pointing at in-repo paths.
"""

from __future__ import annotations

import json
import logging
import os
import shutil
import sys
from pathlib import Path
from typing import Any, Final

logger = logging.getLogger(__name__)

SOAK_DIRNAME: Final = "evolver.py-soak"

#: Round-30 (演进方案.md §11.4 P0-1): human adjudication ledger for gate
#: decisions, stored next to the anchor suite — outside every workspace and
#: never written by the engine. Rows are ``{"event_id", "verdict", "by"}``
#: with ``verdict`` in {true_positive, false_kill}.
GATE_VERIFICATIONS_FILE: Final = "gate-verifications.jsonl"


def soak_root() -> Path:
    from evolver.gep.paths import get_evolver_home

    return get_evolver_home() / SOAK_DIRNAME


def path_is_inside(inner: Path, outer: Path) -> bool:
    """True when *inner* is *outer* or a descendant (after resolve)."""
    try:
        inner.resolve().relative_to(outer.resolve())
        return True
    except (ValueError, OSError):
        return False


def evolution_dir_inside_repo() -> bool:
    """True when the active EVOLUTION_DIR lives inside the git work tree."""
    from evolver.gep.paths import get_evolution_dir, get_repo_root

    repo = get_repo_root(_quiet=True)
    if repo is None:
        return False
    return path_is_inside(get_evolution_dir(), repo)


def exports_shell() -> str:
    from evolver.gep.paths import get_evolver_home

    root = soak_root()
    home = get_evolver_home()
    return (
        f"# generated by evolver soak setup — source this file; do not commit\n"
        f'export EVOLUTION_DIR="{root / "evolution"}"\n'
        f'export GEP_ASSETS_DIR="{root / "gep"}"\n'
        f'export EVOLVER_HOME="{home}"\n'
    )


def setup(*, copy_lessons: bool = True, copy_existing_state: bool = True) -> dict[str, Any]:
    """Create the soak dirs and write ``env.sh``. Idempotent."""
    from evolver.gep.paths import get_workspace_root

    root = soak_root()
    evolution = root / "evolution"
    gep = root / "gep"
    evolution.mkdir(parents=True, exist_ok=True)
    gep.mkdir(parents=True, exist_ok=True)

    copied = False
    if copy_lessons:
        src = get_workspace_root() / "memory" / "evolution" / "LESSONS_LEARNED.md"
        dest = evolution / "LESSONS_LEARNED.md"
        if src.is_file() and not dest.exists():
            shutil.copy2(src, dest)
            copied = True

    copied_assets: list[str] = []
    if copy_existing_state:
        ws = get_workspace_root()
        gep_src = ws / ".evolver" / "gep"
        for name in ("genes.json", "genes.jsonl", "events.jsonl", "autopoiesis_rules.json"):
            src_f = gep_src / name
            dest_f = gep / name
            if src_f.is_file() and not dest_f.exists():
                shutil.copy2(src_f, dest_f)
                copied_assets.append(f"gep/{name}")

        evo_src = ws / "memory" / "evolution"
        for name in ("feedback.jsonl", "autopoiesis.jsonl"):
            src_f = evo_src / name
            dest_f = evolution / name
            if src_f.is_file() and not dest_f.exists():
                shutil.copy2(src_f, dest_f)
                copied_assets.append(f"evolution/{name}")

    env_sh = root / "env.sh"
    env_sh.write_text(exports_shell(), encoding="utf-8")
    return {
        "ok": True,
        "root": str(root),
        "evolution_dir": str(evolution),
        "gep_assets_dir": str(gep),
        "env_sh": str(env_sh),
        "copied_lessons": copied,
        "copied_assets": copied_assets,
    }


def is_test_environment() -> bool:
    """True when executing inside pytest or an isolated test harness."""
    if os.environ.get("PYTEST_CURRENT_TEST"):
        return True
    if os.environ.get("EVOLVER_TEST_MODE") in {"1", "true", "yes"}:
        return True
    return os.environ.get("EVOLVER_NO_PARENT_GIT") == "1"


def maybe_route_to_soak(
    *,
    force: bool = False,
    copy_existing: bool = True,
) -> dict[str, Any]:
    """Interlock: route runtime to $EVOLVER_HOME/evolver.py-soak if inside_repo.

    演进方案.md §11.4 P1 #4: When evolver is executed in a product git worktree
    and not in a test environment, daemon/swarm/mcp writes must not dirty the
    git tree. Auto-route EVOLUTION_DIR and GEP_ASSETS_DIR to the external soak
    layout. Bypassable via EVOLVER_SOAK_ALLOW_INSIDE=1.
    """
    if os.environ.get("EVOLVER_SOAK_ALLOW_INSIDE") in {"1", "true", "yes"} and not force:
        return {"routed": False, "reason": "bypassed_by_env"}

    if not force and is_test_environment():
        return {"routed": False, "reason": "test_environment"}

    if not force and not evolution_dir_inside_repo():
        return {"routed": False, "reason": "already_outside"}

    setup_result = setup(copy_lessons=True, copy_existing_state=copy_existing)
    root = soak_root()
    soak_evo = str(root / "evolution")
    soak_gep = str(root / "gep")

    prev_evo = os.environ.get("EVOLUTION_DIR")
    prev_gep = os.environ.get("GEP_ASSETS_DIR")

    os.environ["EVOLUTION_DIR"] = soak_evo
    os.environ["GEP_ASSETS_DIR"] = soak_gep
    # Sentinel for validation_env(): the two vars above are THIS PROCESS's
    # runtime routing, not operator intent — spawned validation subprocesses
    # (cascade pytest / T0 gate) must not inherit them (round-35, DEBUG #41:
    # the inherited soak routing broke workspace-default path resolution in
    # the eval worktree's own test suite).
    os.environ["EVOLVER_SOAK_ROUTED"] = "1"

    warn_msg = (
        f"[soak] Notice: in-repo runtime detected (inside_repo=True). "
        f"Auto-routed EVOLUTION_DIR and GEP_ASSETS_DIR to {root} "
        f"(set EVOLVER_SOAK_ALLOW_INSIDE=1 to bypass)."
    )
    logger.warning(warn_msg)
    print(warn_msg, file=sys.stderr)

    return {
        "routed": True,
        "soak_root": str(root),
        "evolution_dir": soak_evo,
        "gep_assets_dir": soak_gep,
        "prev_evolution_dir": prev_evo,
        "prev_gep_assets_dir": prev_gep,
        "setup": setup_result,
    }


def gate_verifications_path() -> Path:
    """Anchor-adjacent ledger path for human-adjudicated gate decisions."""
    from evolver.gep.anchor import anchor_dir

    return anchor_dir() / GATE_VERIFICATIONS_FILE


def read_gate_verifications() -> dict[str, str]:
    """Read ``event_id -> verdict`` from the out-of-tree ledger (read-only).

    Missing or malformed rows are skipped, not fatal: this is advisory human
    evidence, and a corrupt ledger must not take the report down with it. The
    engine never writes here — same trust posture as the anchor suite.
    """
    path = gate_verifications_path()
    if not path.is_file():
        return {}
    out: dict[str, str] = {}
    try:
        raw = path.read_text(encoding="utf-8")
    except OSError:
        return {}
    for line in raw.splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            row = json.loads(line)
        except json.JSONDecodeError:
            continue
        if not isinstance(row, dict):
            continue
        event_id = str(row.get("event_id") or "")
        verdict = str(row.get("verdict") or "")
        if event_id and verdict:
            out[event_id] = verdict
    return out


def status(*, event_limit: int = 5000) -> dict[str, Any]:
    """Current path layout + gate-report metrics for the active env.

    Round-49: when the interlock is armed but the operator's shell still
    resolves the in-repo (frozen) ledger, the metrics are computed from the
    SOAK ledger — the live runtime the interlock maintains — with an explicit
    ``metrics_source`` marker. Showing stale in-repo numbers as if current
    misled operators for 20 rounds (same class as the round-47 reason gap).
    """
    import json as _json

    from evolver.gep.acceptance.report import (
        gate_soak_recommendation,
        summarize_acceptance,
    )
    from evolver.gep.asset_store import read_all_events
    from evolver.gep.paths import get_evolution_dir, get_gep_assets_dir

    armed = not is_test_environment()
    inside = evolution_dir_inside_repo()
    if armed and inside:
        soak_events_path = soak_root() / "gep" / "events.jsonl"
        events: list[dict[str, Any]] = []
        if soak_events_path.is_file():
            with soak_events_path.open(encoding="utf-8", errors="replace") as fh:
                for line in fh:
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        events.append(_json.loads(line))
                    except ValueError:
                        continue
        metrics_source = "soak_root"
    else:
        events = read_all_events()
        metrics_source = "active_env"
    metrics = summarize_acceptance(
        events[-max(1, event_limit) :],
        verified=read_gate_verifications(),
    )
    return {
        "ok": True,
        "evolution_dir": str(get_evolution_dir()),
        "gep_assets_dir": str(get_gep_assets_dir()),
        "inside_repo": inside,
        "interlock_armed": armed,
        "soak_root": str(soak_root()),
        "metrics": metrics,
        "metrics_source": metrics_source,
        "recommendation": gate_soak_recommendation(metrics),
    }


__all__ = [
    "GATE_VERIFICATIONS_FILE",
    "SOAK_DIRNAME",
    "evolution_dir_inside_repo",
    "exports_shell",
    "gate_verifications_path",
    "is_test_environment",
    "maybe_route_to_soak",
    "path_is_inside",
    "read_gate_verifications",
    "setup",
    "soak_root",
    "status",
]
