"""Soak environment — keep evolution runtime off the product git tree.

演进方案.md §10: gated_runs 4→20 must use an ``EVOLUTION_DIR`` outside the
repo so daemon/swarm writes do not dirty ``master``. This module creates that
layout under ``$EVOLVER_HOME/evolver.py-soak/`` and reports whether the
current process is still pointing at in-repo paths.
"""

from __future__ import annotations

import shutil
from pathlib import Path
from typing import Any, Final

SOAK_DIRNAME: Final = "evolver.py-soak"


def soak_root() -> Path:
    from evolver.gep.paths import get_evolver_home

    return get_evolver_home() / SOAK_DIRNAME


def path_is_inside(inner: Path, outer: Path) -> bool:
    """True when *inner* is *outer* or a descendant (after resolve)."""
    try:
        inner.resolve().relative_to(outer.resolve())
        return True
    except (ValueError, OSError):
        return False


def evolution_dir_inside_repo() -> bool:
    """True when the active EVOLUTION_DIR lives inside the git work tree."""
    from evolver.gep.paths import get_evolution_dir, get_repo_root

    repo = get_repo_root(_quiet=True)
    if repo is None:
        return False
    return path_is_inside(get_evolution_dir(), repo)


def exports_shell() -> str:
    from evolver.gep.paths import get_evolver_home

    root = soak_root()
    home = get_evolver_home()
    return (
        f"# generated by evolver soak setup — source this file; do not commit\n"
        f'export EVOLUTION_DIR="{root / "evolution"}"\n'
        f'export GEP_ASSETS_DIR="{root / "gep"}"\n'
        f'export EVOLVER_HOME="{home}"\n'
    )


def setup(*, copy_lessons: bool = True) -> dict[str, Any]:
    """Create the soak dirs and write ``env.sh``. Idempotent."""
    from evolver.gep.paths import get_workspace_root

    root = soak_root()
    evolution = root / "evolution"
    gep = root / "gep"
    evolution.mkdir(parents=True, exist_ok=True)
    gep.mkdir(parents=True, exist_ok=True)

    copied = False
    if copy_lessons:
        src = get_workspace_root() / "memory" / "evolution" / "LESSONS_LEARNED.md"
        dest = evolution / "LESSONS_LEARNED.md"
        if src.is_file() and not dest.exists():
            shutil.copy2(src, dest)
            copied = True

    env_sh = root / "env.sh"
    env_sh.write_text(exports_shell(), encoding="utf-8")
    return {
        "ok": True,
        "root": str(root),
        "evolution_dir": str(evolution),
        "gep_assets_dir": str(gep),
        "env_sh": str(env_sh),
        "copied_lessons": copied,
    }


def status(*, event_limit: int = 5000) -> dict[str, Any]:
    """Current path layout + gate-report metrics for the active env."""
    from evolver.gep.acceptance.report import (
        gate_soak_recommendation,
        summarize_acceptance,
    )
    from evolver.gep.asset_store import read_all_events
    from evolver.gep.paths import get_evolution_dir, get_gep_assets_dir

    metrics = summarize_acceptance(read_all_events()[-max(1, event_limit) :])
    return {
        "ok": True,
        "evolution_dir": str(get_evolution_dir()),
        "gep_assets_dir": str(get_gep_assets_dir()),
        "inside_repo": evolution_dir_inside_repo(),
        "soak_root": str(soak_root()),
        "metrics": metrics,
        "recommendation": gate_soak_recommendation(metrics),
    }


__all__ = [
    "SOAK_DIRNAME",
    "evolution_dir_inside_repo",
    "exports_shell",
    "path_is_inside",
    "setup",
    "soak_root",
    "status",
]
