"""Wiki patterns projection (S27.2) — machine state → human-readable pages.

No Node.js equivalent; evolver.py addition.

Plan 演进方案_wikiskill对照版.md §27.2: the wiki's ``patterns/`` pages are a
human-readable PROJECTION of machine-layer state (LESSONS_LEARNED friction
points, memory_graph preferred genes). Raw JSONL stays the machine layer;
these pages are regenerated wholesale on each projection (idempotent —
no append-only obligation, they are derived views). Triggered by
``evolver report``.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from evolver.gep import wiki
from evolver.gep.living_memory import load_living_memory


def _friction_page(memory: dict[str, Any]) -> str:
    points = memory.get("recent_friction_points") or []
    total = memory.get("total_friction_points", len(points))
    lines = [
        "# Living-Memory Friction (projected)",
        "",
        f"Projected from LESSONS_LEARNED.md ({total} total points). "
        "Deterministic content; the wiki git log records projection times.",
        "",
    ]
    if not points:
        lines.append("_No friction points recorded — nothing to avoid yet._")
        return "\n".join(lines) + "\n"
    lines.append("| category | friction | status |")
    lines.append("|---|---|---|")
    for fp in points:
        cat = str(fp.get("category", "unknown"))
        desc = str(fp.get("description", ""))[:160].replace("|", "\\|")
        status = str(fp.get("status", "open"))
        lines.append(f"| {cat} | {desc} | {status} |")
    return "\n".join(lines) + "\n"


def _preferred_page(state: dict[str, Any]) -> str:
    prefs = state.get("preferred_by_signal") or {}
    lines = [
        "# Preferred Genes per Signal (projected)",
        "",
        "Projected from memory_graph_state.json.",
        "",
    ]
    if not prefs:
        lines.append("_No signal-gene preferences accumulated yet._")
        return "\n".join(lines) + "\n"
    lines.append("| signal key | preferred genes |")
    lines.append("|---|---|")
    for key in sorted(prefs):
        genes = prefs[key]
        if isinstance(genes, dict):
            items = [f"{g}×{w}" for g, w in sorted(genes.items(), key=lambda kv: -kv[1])[:5]]
        else:
            items = [str(g) for g in list(genes)[:5]]
        lines.append(f"| {key} | {', '.join(items) if items else '—'} |")
    return "\n".join(lines) + "\n"


def project_patterns() -> list[Path]:
    """Regenerate ``wiki/patterns/*.md`` from machine-layer state; audit-commit."""
    from evolver.gep.memory_graph import _read_state

    root = wiki.ensure() / "patterns"
    pages: list[tuple[str, str]] = [
        ("friction.md", _friction_page(load_living_memory())),
        ("preferred-genes.md", _preferred_page(_read_state())),
    ]
    written: list[Path] = []
    for name, body in pages:
        path = root / name
        path.write_text(body, encoding="utf-8", newline="\n")
        written.append(path)
    index = "\n".join(
        [
            "# Pattern Index",
            "",
            "Human-readable projection of what the evolution loop has learned.",
            "Regenerated by `evolver report` (S27.2); raw JSONL is the machine layer.",
            "",
            *[f"- [{name}](patterns/{name})" for name, _ in pages],
            "",
        ]
    )
    (root.parent / "index.md").write_text(index, encoding="utf-8", newline="\n")
    wiki.commit("wiki: patterns projection")
    return written


__all__ = ["project_patterns"]
