#!/usr/bin/env python3
"""Inventory every environment variable the codebase reads (S25.5).

演进方案_wikiskill对照版.md §S25.5: ~196 unique EVOLVER_*/EVOMAP_*/A2A_*/path
variables were claimed; this script produces the auditable registry that
S30.4 governance will prune against.

Usage:
    python scripts/env_inventory.py                 # print summary table
    python scripts/env_inventory.py --markdown out  # write a markdown registry

Pure stdlib AST scan: finds env_str/env_int/env_bool/env_float calls,
os.environ/os.getenv accesses, and EVOLVER_FF_ flag env names.
"""

from __future__ import annotations

import argparse
import ast
import re
import sys
from collections import defaultdict
from pathlib import Path

ENV_HELPERS = {"env_str", "env_int", "env_bool", "env_float", "env_float_opt", "env_str_opt"}
DIRECT = {"getenv"}
FF_RE = re.compile(r"EVOLVER_FF_[A-Z0-9_]+")
PREFIXES = ("EVOLVER_", "EVOMAP_", "A2A_", "OPENCLAW_", "GEP_", "EVOLUTION_", "MEMORY_")


def _first_string_arg(call: ast.Call) -> str | None:
    if call.args and isinstance(call.args[0], ast.Constant) and isinstance(call.args[0].value, str):
        return call.args[0].value
    for kw in call.keywords:
        if (
            kw.arg == "name"
            and isinstance(kw.value, ast.Constant)
            and isinstance(kw.value.value, str)
        ):
            return kw.value.value
    return None


class EnvScanner(ast.NodeVisitor):
    def __init__(self) -> None:
        self.found: dict[str, set[str]] = defaultdict(set)

    def visit_Call(self, node: ast.Call) -> None:
        func = node.func
        name = ""
        if isinstance(func, ast.Name):
            name = func.id
        elif isinstance(func, ast.Attribute):
            name = func.attr
        if name in ENV_HELPERS:
            env = _first_string_arg(node)
            if env:
                self.found[env].add(f"helper:{name}")
        elif name in DIRECT and isinstance(func, ast.Attribute):
            env = _first_string_arg(node)
            if env:
                self.found[env].add("os.getenv")
        self.generic_visit(node)

    def visit_Attribute(self, node: ast.Attribute) -> None:
        # generic os.environ subscript reads are covered by scanning the
        # constant env names (visit_Constant); nothing to mark here.
        self.generic_visit(node)

    def visit_Constant(self, node: ast.Constant) -> None:
        if isinstance(node.value, str) and node.value.startswith(PREFIXES):
            self.found[node.value].add("constant")
        self.generic_visit(node)


def scan_repo(root: Path) -> dict[str, set[str]]:
    registry: dict[str, set[str]] = defaultdict(set)
    for path in sorted((root / "src").rglob("*.py")):
        try:
            tree = ast.parse(path.read_text(encoding="utf-8", errors="replace"))
        except SyntaxError:
            continue
        scanner = EnvScanner()
        scanner.visit(tree)
        for env, hows in scanner.found.items():
            registry[env].update(hows)
    # feature-flag env names are implicit: EVOLVER_FF_<FLAG>
    try:
        sys.path.insert(0, str(root / "src"))
        from evolver.gep.feature_flags import DEFAULT_FLAGS

        for flag in DEFAULT_FLAGS:
            registry[f"EVOLVER_FF_{flag.upper()}"].add("feature_flag")
    except Exception:
        pass
    return registry


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=str(Path(__file__).resolve().parent.parent))
    parser.add_argument("--markdown", default=None, help="Write the registry as markdown")
    args = parser.parse_args()

    root = Path(args.root)
    registry = scan_repo(root)
    grouped: dict[str, list[str]] = defaultdict(list)
    for env in registry:
        prefix = next((p for p in PREFIXES if env.startswith(p)), "OTHER")
        grouped[prefix].append(env)

    print(f"Total unique environment variables: {len(registry)}")
    for prefix in sorted(grouped):
        print(f"  {prefix:<12} {len(grouped[prefix])}")

    if args.markdown:
        lines = [
            "# Environment Variable Registry (S25.5)",
            "",
            f"Auto-generated by `scripts/env_inventory.py` — {len(registry)} unique variables.",
            "S30.4 governance prunes against this registry.",
            "",
        ]
        for prefix in sorted(grouped):
            lines += [
                f"## {prefix}* ({len(grouped[prefix])})",
                "",
                "| Variable | Mechanism |",
                "|---|---|",
            ]
            for env in sorted(grouped[prefix]):
                lines.append(f"| `{env}` | {', '.join(sorted(registry[env]))} |")
            lines.append("")
        Path(args.markdown).write_text("\n".join(lines), encoding="utf-8")
        print(f"wrote {args.markdown}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
