"""opencode IDE adapter.

Equivalent to ``evolver/src/adapters/opencode.js``.
Installs/uninstalls evolver plugin into ``.opencode/plugins/evolver.js``.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from evolver.adapters.hook_adapter import (
    assert_safe_config_dir,
    copy_hook_scripts,
    remove_hook_scripts,
    remove_marked_section,
)

HOOK_SCRIPTS_DIR_NAME = "hooks"
PLUGINS_DIR_NAME = "plugins"
PLUGIN_FILE_NAME = "evolver.js"
EVOLVER_MARKER = "<!-- evolver-evolution-memory -->"
PLUGIN_HEADER = "// _evolver_managed: true (do not remove this line)"


def build_plugin_source(hooks_dir_absolute: Path) -> str:
    """Build the opencode plugin JavaScript source.

    The plugin shells out to the same Python scripts that every other
    evolver adapter uses, so runtime behavior stays consistent.
    """
    from evolver.uv_runtime import build_module_command

    hooks_dir_str = str(hooks_dir_absolute).replace("\\", "/")

    def _cmd(mod: str) -> list[str]:
        return [p.replace("\\", "/") for p in build_module_command(mod)]

    cmds = {
        "session_start": _cmd("evolver.adapters.scripts.session_start"),
        "signal_detect": _cmd("evolver.adapters.scripts.signal_detect"),
        "session_end": _cmd("evolver.adapters.scripts.session_end"),
    }
    cmds_json = json.dumps(cmds)
    return f"""{PLUGIN_HEADER}
// Auto-generated by `evolver setup-hooks --platform=opencode`.
// See https://opencode.ai/docs/plugins/ for the plugin API.
//
// This plugin wires opencode events to the three evolver hook scripts:
//   session.created      -> evolver-session-start.py  (inject memory)
//   tool.execute.after   -> evolver-signal-detect.py  (detect signals on writes/edits)
//   session.idle         -> evolver-session-end.py    (record outcome)
//
// Each script is a stdin/stdout JSON filter -- nothing else is shared with
// opencode, so removing this file fully detaches evolver from opencode.
// Launcher resolved via evolver.uv_runtime (python / uv run / uvx).

const {{ spawnSync }} = require('node:child_process');
const path = require('node:path');

const HOOKS_DIR = {json.dumps(hooks_dir_str)};
const CMDS = {cmds_json};

function runHook(scriptName, payload, timeoutMs) {{
  try {{
    const parts = CMDS[scriptName];
    if (!parts || !parts.length) return {{}};
    const result = spawnSync(parts[0], parts.slice(1), {{
      input: JSON.stringify(payload || {{}}),
      encoding: 'utf8',
      timeout: timeoutMs,
    }});
    if (!result || !result.stdout) return {{}};
    try {{ return JSON.parse(result.stdout); }} catch {{ return {{}}; }}
  }} catch {{
    return {{}};
  }}
}}

const Evolver = async () => ({{
  event: async ({{ event }}) => {{
    if (!event || typeof event.type !== 'string') return;
    if (event.type === 'session.created') {{
      runHook('session_start', {{
        session_id: event.properties && event.properties.info && event.properties.info.id,
      }}, 3000);
      return;
    }}
    if (event.type === 'session.idle') {{
      runHook('session_end', {{
        session_id: event.properties && event.properties.sessionID,
      }}, 8000);
    }}
  }},
  'tool.execute.after': async (input, output) => {{
    if (!input || typeof input.tool !== 'string') return;
    if (input.tool !== 'write' && input.tool !== 'edit') return;
    runHook('signal_detect', {{
      tool_input: (output && output.args) || {{}},
      tool_response: (output && output.output) || (output && output.result) || {{}},
    }}, 2000);
  }},
}});

module.exports = {{ Evolver }};
module.exports.default = Evolver;
"""


def build_agents_md_section() -> str:
    return f"""{EVOLVER_MARKER}
## Evolution Memory (Evolver)

This project uses evolver for self-evolution. Hooks automatically:
1. Inject recent evolution memory at session start
2. Detect evolution signals during file edits
3. Record outcomes at session end

For substantive tasks, call `gep_recall` before work and `gep_record_outcome` after.
Signals: log_error, perf_bottleneck, user_feature_request, capability_gap, deployment_issue, test_failure."""


def _append_section_to_file(file_path: Path, marker: str, content: str) -> bool:
    existing = ""
    if file_path.exists():
        existing = file_path.read_text(encoding="utf-8")
    if marker in existing:
        return False
    separator = "\n\n" if existing and not existing.endswith("\n") else "\n"
    file_path.write_text(existing + separator + content + "\n", encoding="utf-8")
    return True


def _is_evolver_managed_plugin_file(file_path: Path) -> bool:
    try:
        if not file_path.exists():
            return False
        raw = file_path.read_text(encoding="utf-8")
        return "_evolver_managed: true" in raw
    except OSError:
        return False


def _write_plugin_file(plugins_dir: Path, source: str) -> Path:
    plugins_dir.mkdir(parents=True, exist_ok=True)
    dest = plugins_dir / PLUGIN_FILE_NAME
    tmp = dest.with_suffix(dest.suffix + ".tmp")
    tmp.write_text(source, encoding="utf-8")
    tmp.replace(dest)
    return dest


def install(
    *,
    config_root: Path,
    evolver_root: Path,
    force: bool = False,
) -> dict[str, Any]:
    opencode_dir = config_root / ".opencode"
    hooks_dir = opencode_dir / HOOK_SCRIPTS_DIR_NAME
    plugins_dir = opencode_dir / PLUGINS_DIR_NAME
    plugin_path = plugins_dir / PLUGIN_FILE_NAME
    agents_md_path = config_root / "AGENTS.md"
    assert_safe_config_dir(
        opencode_dir, ".opencode", subdirs=[HOOK_SCRIPTS_DIR_NAME, PLUGINS_DIR_NAME]
    )

    if not force and _is_evolver_managed_plugin_file(plugin_path):
        print("[opencode] Evolver plugin already installed. Use --force to overwrite.")
        _print_post_install_notice(plugin_path)
        return {"ok": True, "skipped": True, "plugin_path": str(plugin_path)}

    opencode_dir.mkdir(parents=True, exist_ok=True)

    written = _write_plugin_file(plugins_dir, build_plugin_source(hooks_dir))
    print(f"[opencode] Wrote {written}")

    copied = copy_hook_scripts(hooks_dir, evolver_root)
    print(f"[opencode] Copied {len(copied)} hook scripts to {hooks_dir}")

    injected = _append_section_to_file(agents_md_path, EVOLVER_MARKER, build_agents_md_section())
    if injected:
        print(f"[opencode] Injected evolution section into {agents_md_path}")

    print("[opencode] Installation complete.")
    _print_post_install_notice(written)

    return {
        "ok": True,
        "platform": "opencode",
        "plugin_path": str(written),
        "files": [str(written), str(agents_md_path)] + [str(c) for c in copied],
    }


def _print_post_install_notice(plugin_path: Path) -> None:
    print("")
    print("[opencode] Restart opencode for the plugin to take effect.")
    print("[opencode] Note: this is a SERVER plugin (event hooks). It will NOT appear in")
    print('[opencode]       the TUI "Plugins" tab -- that tab only lists TUI plugins')
    print("[opencode]       (registered via tui.json). The plugin is still loaded and")
    print("[opencode]       running silently in the background.")
    print("[opencode] To verify the plugin is loaded, run:")
    print(
        f"[opencode]   opencode --print-logs --log-level INFO debug config 2>&1 | grep {json.dumps(str(plugin_path))}"
    )
    print("[opencode] Or run:")
    print("[opencode]   evolver setup-hooks --platform=opencode --verify")


def verify(*, config_root: Path) -> dict[str, Any]:
    opencode_dir = config_root / ".opencode"
    hooks_dir = opencode_dir / HOOK_SCRIPTS_DIR_NAME
    plugins_dir = opencode_dir / PLUGINS_DIR_NAME
    plugin_path = plugins_dir / PLUGIN_FILE_NAME
    agents_md_path = config_root / "AGENTS.md"
    expected_scripts = [
        "session_start.py",
        "signal_detect.py",
        "session_end.py",
    ]

    checks: list[dict[str, Any]] = []

    plugin_exists = plugin_path.exists()
    checks.append(
        {
            "id": "plugin_file_present",
            "ok": plugin_exists,
            "detail": str(plugin_path) if plugin_exists else f"missing: {plugin_path}",
        }
    )

    managed = plugin_exists and _is_evolver_managed_plugin_file(plugin_path)
    checks.append(
        {
            "id": "plugin_managed_marker",
            "ok": managed,
            "detail": (
                "first line contains _evolver_managed: true"
                if managed
                else "plugin file is not evolver-managed (was it edited or replaced by another tool?)"
            ),
        }
    )

    plugin_loadable = False
    plugin_load_error: str | None = None
    if plugin_exists:
        # We cannot require() JS from Python, so we do a structural check.
        try:
            raw = plugin_path.read_text(encoding="utf-8")
            plugin_loadable = "module.exports" in raw and "Evolver" in raw
            if not plugin_loadable:
                plugin_load_error = "no module.exports / Evolver export found"
        except OSError as exc:
            plugin_load_error = str(exc)

    checks.append(
        {
            "id": "plugin_loadable",
            "ok": plugin_loadable,
            "detail": (
                "structural check passed (module.exports + Evolver)"
                if plugin_loadable
                else f"structural check failed: {plugin_load_error or 'unknown'}"
            ),
        }
    )

    missing_scripts = [name for name in expected_scripts if not (hooks_dir / name).exists()]
    checks.append(
        {
            "id": "hook_scripts_present",
            "ok": len(missing_scripts) == 0,
            "detail": (
                f"all {len(expected_scripts)} hook scripts present in {hooks_dir}"
                if not missing_scripts
                else f"missing: {', '.join(missing_scripts)}"
            ),
        }
    )

    agents_md_has_section = False
    try:
        if agents_md_path.exists():
            agents_md_has_section = EVOLVER_MARKER in agents_md_path.read_text(encoding="utf-8")
    except OSError:
        pass

    checks.append(
        {
            "id": "agents_md_section",
            "ok": agents_md_has_section,
            "detail": (
                "AGENTS.md contains evolution memory section"
                if agents_md_has_section
                else "AGENTS.md is missing or has no evolution section (re-run install)"
            ),
        }
    )

    all_ok = all(c["ok"] for c in checks)

    return {
        "ok": all_ok,
        "plugin_path": str(plugin_path),
        "hooks_dir": str(hooks_dir),
        "config_root": str(config_root),
        "checks": checks,
        "note": (
            "Plugin is installed and structurally valid. opencode's TUI 'Plugins' tab will not list it -- that tab only shows TUI plugins."
            if all_ok
            else "One or more checks failed. Re-run `evolver setup-hooks --platform=opencode --force` to repair."
        ),
    }


def print_verify_report(report: dict[str, Any]) -> None:
    print("[opencode] Verify report")
    print(f"[opencode]   plugin path : {report.get('plugin_path')}")
    print(f"[opencode]   hooks dir   : {report.get('hooks_dir')}")
    print(f"[opencode]   config root : {report.get('config_root')}")
    print("[opencode] Checks:")
    for c in report.get("checks", []):
        status = "[OK]  " if c.get("ok") else "[FAIL]"
        print(f"[opencode]   {status} {c.get('id')} -- {c.get('detail')}")
    print(f"[opencode] {report.get('note', '')}")


def uninstall(
    *,
    config_root: Path,
    evolver_root: Path,
) -> dict[str, Any]:
    opencode_dir = config_root / ".opencode"
    hooks_dir = opencode_dir / HOOK_SCRIPTS_DIR_NAME
    plugins_dir = opencode_dir / PLUGINS_DIR_NAME
    plugin_path = plugins_dir / PLUGIN_FILE_NAME
    agents_md_path = config_root / "AGENTS.md"
    assert_safe_config_dir(
        opencode_dir, ".opencode", subdirs=[HOOK_SCRIPTS_DIR_NAME, PLUGINS_DIR_NAME]
    )

    changed = False

    if _is_evolver_managed_plugin_file(plugin_path):
        try:
            plugin_path.unlink()
            changed = True
        except OSError:
            pass

    scripts = remove_hook_scripts(hooks_dir)
    if scripts > 0:
        changed = True

    if remove_marked_section(agents_md_path, EVOLVER_MARKER):
        changed = True

    print(
        "[opencode] Uninstalled evolver plugin and hooks."
        if changed
        else "[opencode] No evolver plugin found to uninstall."
    )

    return {"ok": True, "removed": changed}
