"""IDE hook installer for evolver.

Supports Cursor, Claude Code, VS Code, and a generic markdown fallback.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Sequence


SUPPORTED_PLATFORMS: Sequence[str] = ("cursor", "claude-code", "vscode", "generic")

_CURSOR_RULE = """---
description: Enforce GEP (Genetic Evolution Protocol) rules when editing evolver-related code
globs: "**/*.py", "**/*.js", "**/*.ts", "**/*.md", "**/*.json"
alwaysApply: true
---

# GEP Coding Rules

You are assisting the `@evomap/evolver` project — a self-evolving AI-agent engine.

## Core Principles
1. **Minimal changes** — prefer small, targeted edits over large refactors.
2. **Test coverage** — every new feature or bug fix must include tests.
3. **Type safety** — use Python 3.12+ type annotations; avoid `Any` where possible.
4. **Async-first** — I/O-bound operations must use `asyncio`; sync I/O is a last resort.
5. **Environment-aware** — respect `EVOLVER_*` env vars and the config module.

## File Conventions
- Source lives under `src/evolver/`
- Tests live under `tests/`
- Assets (genes, capsules) live under `src/evolver/assets/gep/`
- Never commit secrets; read them from env or `.env` files.

## Before Solidifying
- Run `uv run pytest tests/ -v`
- Run `uv run evolver run` for a manual smoke test
- Check `blast_radius` stays under caps (60 files / 20k lines)

## Prohibited
- Blocking network calls in async paths
- Hard-coded paths that ignore `EVOLVER_REPO_ROOT`
- Mutations without validation steps
- `print()` for logging — use the logger module

For full protocol see: https://github.com/EvoMap/evolver/blob/main/DESIGN.md
"""

_CURSOR_MCP = {
    "mcpServers": {
        "evolver": {
            "command": "uv",
            "args": ["run", "evolver", "run"],
            "env": {},
        }
    }
}

_CLAUDE_COMMANDS = {
    "evolver-run": {
        "name": "evolver-run",
        "description": "Run one evolver evolution cycle",
        "prompt": "Run `uv run evolver run` in the terminal and report the results. If solidify is pending, suggest `evolver review`.",
    },
    "evolver-review": {
        "name": "evolver-review",
        "description": "Review pending solidify state",
        "prompt": "Run `uv run evolver review` and help the user decide whether to apply, rollback, or skip the pending changes.",
    },
}

_CLAUDE_MD_HEADER = """# Evolver Project Context

> Auto-generated by `evolver setup-hooks`. Edit freely — this is your project memory.

## Quick Commands
- Run one cycle: `uv run evolver run`
- Daemon loop: `uv run evolver --loop`
- Solidify pending: `uv run evolver solidify`
- Review changes: `uv run evolver review`
- Run tests: `uv run pytest tests/ -v`

## Architecture
- `src/evolver/gep/` — core protocol (signals, selector, strategy, mutation, bridge, solidify)
- `src/evolver/evolve/` — evolution runner and loop
- `src/evolver/ops/` — cleanup, narrative, execution_trace
- `src/evolver/webui/` — FastAPI dashboard
- `src/evolver/adapters/` — IDE hooks and integrations

## Coding Rules
1. Minimal changes, maximal clarity.
2. Every feature needs tests.
3. Use Python 3.12+ annotations.
4. Async for I/O; sync only for CPU-bound work.
5. Respect `EVOLVER_*` environment variables.
6. No hard-coded secrets or paths.

## GEP Reminder
When suggesting code changes, think in terms of **genes** (reusable strategies) and **capsules** (injected knowledge). If a pattern recurs, it might be a candidate for a new gene.
"""

_VSCODE_SETTINGS = {
    "python.analysis.typeCheckingMode": "strict",
    "python.testing.pytestEnabled": True,
    "python.testing.autoTestDiscoverOnSaveEnabled": True,
    "editor.formatOnSave": True,
    "editor.rulers": [88, 120],
    "files.exclude": {
        "**/__pycache__": True,
        "**/.pytest_cache": True,
        "**/.mypy_cache": True,
    },
}

_GENERIC_HOOK = """# Evolver IDE Hook

This project uses `@evomap/evolver` for self-evolution.

## Integration Checklist
- [ ] Install evolver: `pip install evolver` or `uv add --dev evolver`
- [ ] Run initial cycle: `evolver run`
- [ ] Review `evolver review` before committing AI-generated changes
- [ ] Keep `tests/` green — evolver respects test results as fitness signals

## Recommended IDE Configurations

### Cursor
Create `.cursor/rules/evolver-gep.mdc` with the Cursor rule from:
`evolver setup-hooks --platform=cursor`

### Claude Code
Create `.claude/AGENTS.md` with project context from:
`evolver setup-hooks --platform=claude-code`

### VS Code
Update `.vscode/settings.json` with strict Python settings from:
`evolver setup-hooks --platform=vscode`

## Useful Aliases
```bash
alias evrun='uv run evolver run'
alias evloop='uv run evolver --loop'
alias evsol='uv run evolver solidify'
alias evrev='uv run evolver review'
alias evtest='uv run pytest tests/ -v'
```
"""


def _detect_platform(project_dir: Path) -> str | None:
    """Auto-detect IDE by looking for existing config directories."""
    if (project_dir / ".cursor").exists():
        return "cursor"
    if (project_dir / ".claude").exists():
        return "claude-code"
    if (project_dir / ".vscode").exists():
        return "vscode"
    return None


def _write_cursor_hook(project_dir: Path, force: bool, dry_run: bool) -> list[str]:
    rules_dir = project_dir / ".cursor" / "rules"
    target = rules_dir / "evolver-gep.mdc"
    mcp_target = project_dir / ".cursor" / "mcp.json"
    msgs: list[str] = []
    if target.exists() and not force:
        msgs.append(f"SKIP cursor hook (exists): {target}")
    else:
        if dry_run:
            msgs.append(f"WOULD write cursor hook: {target}")
        else:
            rules_dir.mkdir(parents=True, exist_ok=True)
            target.write_text(_CURSOR_RULE, encoding="utf-8")
            msgs.append(f"OK cursor hook: {target}")

    if mcp_target.exists() and not force:
        msgs.append(f"SKIP cursor mcp (exists): {mcp_target}")
    else:
        if dry_run:
            msgs.append(f"WOULD write cursor mcp: {mcp_target}")
        else:
            mcp_target.parent.mkdir(parents=True, exist_ok=True)
            mcp_target.write_text(json.dumps(_CURSOR_MCP, indent=2) + "\n", encoding="utf-8")
            msgs.append(f"OK cursor mcp: {mcp_target}")
    return msgs


def _write_claude_hook(project_dir: Path, force: bool, dry_run: bool) -> list[str]:
    claude_dir = project_dir / ".claude"
    target = claude_dir / "AGENTS.md"
    cmds_dir = claude_dir / "commands"
    msgs: list[str] = []
    if target.exists() and not force:
        msgs.append(f"SKIP claude hook (exists): {target}")
    else:
        if dry_run:
            msgs.append(f"WOULD write claude hook: {target}")
        else:
            claude_dir.mkdir(parents=True, exist_ok=True)
            target.write_text(_CLAUDE_MD_HEADER, encoding="utf-8")
            msgs.append(f"OK claude hook: {target}")

    for cmd_name, cmd_data in _CLAUDE_COMMANDS.items():
        cmd_target = cmds_dir / f"{cmd_name}.json"
        if cmd_target.exists() and not force:
            msgs.append(f"SKIP claude command (exists): {cmd_target}")
            continue
        if dry_run:
            msgs.append(f"WOULD write claude command: {cmd_target}")
            continue
        cmds_dir.mkdir(parents=True, exist_ok=True)
        cmd_target.write_text(json.dumps(cmd_data, indent=2) + "\n", encoding="utf-8")
        msgs.append(f"OK claude command: {cmd_target}")
    return msgs


def _write_vscode_hook(project_dir: Path, force: bool, dry_run: bool) -> list[str]:
    vscode_dir = project_dir / ".vscode"
    target = vscode_dir / "settings.json"
    msgs: list[str] = []
    existing: dict = {}
    if target.exists():
        if not force:
            msgs.append(f"SKIP vscode hook (exists): {target}")
            return msgs
        try:
            existing = json.loads(target.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            existing = {}
    merged = {**existing, **_VSCODE_SETTINGS}
    if dry_run:
        msgs.append(f"WOULD write vscode hook: {target}")
        return msgs
    vscode_dir.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(merged, indent=4) + "\n", encoding="utf-8")
    msgs.append(f"OK vscode hook: {target}")
    return msgs


def _write_generic_hook(project_dir: Path, force: bool, dry_run: bool) -> list[str]:
    target = project_dir / "EVOLVER_HOOK.md"
    msgs: list[str] = []
    if target.exists() and not force:
        msgs.append(f"SKIP generic hook (exists): {target}")
        return msgs
    if dry_run:
        msgs.append(f"WOULD write generic hook: {target}")
        return msgs
    target.write_text(_GENERIC_HOOK, encoding="utf-8")
    msgs.append(f"OK generic hook: {target}")
    return msgs


def install_hooks(
    *,
    platform: str = "auto",
    project_dir: str | Path = ".",
    force: bool = False,
    dry_run: bool = False,
) -> dict:
    """Install IDE hooks for the given platform.

    Returns a result dict with ``ok``, ``messages``, and ``platform`` keys.
    """
    pdir = Path(project_dir).resolve()
    if not pdir.is_dir():
        return {"ok": False, "error": f"Not a directory: {pdir}", "messages": []}

    chosen = platform
    if chosen == "auto":
        detected = _detect_platform(pdir)
        if detected:
            chosen = detected
        else:
            chosen = "generic"

    if chosen not in SUPPORTED_PLATFORMS:
        return {
            "ok": False,
            "error": f"Unsupported platform '{chosen}'. Choose from: {', '.join(SUPPORTED_PLATFORMS)} or auto.",
            "messages": [],
        }

    msgs: list[str] = []
    if chosen == "cursor":
        msgs.extend(_write_cursor_hook(pdir, force, dry_run))
    elif chosen == "claude-code":
        msgs.extend(_write_claude_hook(pdir, force, dry_run))
    elif chosen == "vscode":
        msgs.extend(_write_vscode_hook(pdir, force, dry_run))
    elif chosen == "generic":
        msgs.extend(_write_generic_hook(pdir, force, dry_run))

    return {"ok": True, "platform": chosen, "messages": msgs}
